name: gocast_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  provider: ^6.1.1
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/logos/tum-logo-blue.png