name: gocast_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  tuple: ^2.0.1
  bloc: ^8.1.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^5.8.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  uni_links: ^0.5.1
  flutter_riverpod: ^2.4.9
  rxdart: ^0.27.7
  grpc: ^3.2.4
  dio: ^5.4.0
  fixnum: ^1.1.0
  protobuf: ^3.1.0
  logger: ^2.0.2+1
  flutter_secure_storage: ^9.0.0
  video_player: ^2.8.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  chewie: ^1.7.4
  url_launcher: ^6.2.3
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  protoc_plugin: ^21.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/
